<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\MechanicShop.Contracts.csproj" />
    <ProjectReference Include="..\MechanicShop.Application\MechanicShop.Application.csproj" />
  </ItemGroup>

</Project>
